### ISSUE TITLE
lambda function for howto returns error on invocation

### ISSUE THREAD

**Issue by justindeardorff** [alexa/skill-sample-nodejs-howto#48] opened 2018-04-25 14:24 UTC
When following the setup/install instructions as is, the lambda function created returns an error on invocation.

When I instead choose to use the Blueprint setup option with [alexa-skill-kit-sdk-howtoskill] as the blueprint template, the function works properly.

**Comment by franklin-lobb** [comment] 2019-03-10 07:51
will investigate

**Comment by franklin-lobb** [comment] 2019-03-27 04:12
could not reproduce with current instructions and SAR app.  Closing...

**Closed by franklin-lobb** 2019-03-27 04:12 UTC
